### ISSUE TITLE
possible crates.io release?

### ISSUE THREAD

**Issue by kleb6** [jmagnuson/libevent-rs#21]
thanks! -- what do you think about initiating a crates.io release for these changes?

_Originally posted by @kleb6 in https://github.com/jmagnuson/libevent-rs/issues/19#issuecomment-1444973639_

**Comment by jmagnuson** [comment]
[libevent-sys 0.2.6](https://crates.io/crates/libevent-sys/0.2.6) has been published to crates.io!

**Comment by kleb6** [comment]
thanks!! much appreciated!! 🌿🌿😃
